import difflib
import re
import streamlit as st

# 1. 페이지 기본 설정 (가장 위에 배치)
st.set_page_config(page_title="대학영어 워크북 영작하기", layout="wide")


# 2. 텍스트 비교 및 차이점 HTML 생성 함수
def get_diff_html(correct, user):
    correct_words = re.findall(r"\S+", correct)
    user_words = re.findall(r"\S+", user)

    diff = list(difflib.ndiff(correct_words, user_words))

    res = []
    for token in diff:
        word = token[2:]
        if token.startswith("  "):
            res.append(f"<span style='color: black;'>{word}</span>")
        elif token.startswith("- "):
            res.append(
                f"<span style='color: blue; text-decoration: underline;' title='빠뜨린 단어'>{word}</span>"
            )
        elif token.startswith("+ "):
            res.append(
                f"<span style='color: red; text-decoration: line-through;' title='틀린 단어'>{word}</span>"
            )

    html_str = " ".join(res)
    return f'<div style="background-color: #f9f9f9; padding: 15px; border-radius: 5px; line-height: 1.6; font-size: 16px;">{html_str}</div>'


# 3. 데이터 정의
unit01_data = [
    {
        "part": "Part 1",
        "korean": (
            "바이러스는 유기체의 살아 있는 세포 내에서만 복제되는 초미세한"
            " 전염성 물질이다. 바이러스는 동물과 식물에서부터 미생물까지 모든"
            " 생명체를 감염시킨다. 바이러스 연구는 바이러스학이라고 하며, 이는"
            " 미생물학의 일부이다. 바이러스는 단백질 보호막으로 둘러싸인 유전"
            " 물질로 구성되어 있어 세균보다 죽이기가 더 어렵다. 바이러스"
            " 감염으로 인한 가벼운 질병의 경우, 질병이 자연스럽게 진행되도록 하는"
            " 것이 최선의 전략이다. 세균 감염과 싸우도록 고안된 항생제가"
            " 바이러스에 대해서는 효능이 부족하다는 것을 인식하는 것이 중요하다."
            " 항생제는 바이러스를 죽이지 않으며 항생제를 사용하는 것은 항생제"
            " 내성으로 이어질 뿐이다."
        ),
        "english": (
            "A virus is a submicroscopic infectious agent that replicates only"
            " inside the living cells of an organism. Viruses infect all life"
            " forms, from animals and plants to microorganisms. The study of"
            " viruses is called virology, which is a part of microbiology."
            " Viruses consist of genetic materials surrounded by a protective"
            " coat of protein, so they are more difficult to kill than"
            " bacteria. In the case of a minor ailment induced by a viral"
            " infection, the optimal strategy is to allow the malady to"
            " progress naturally. It is crucial to recognize that antibiotics,"
            " designed to combat bacterial infections, lack efficacy against"
            " viral entities. Antibiotics do not kill viruses and the use of"
            " them just leads to antibiotic resistance."
        ),
    },
    {
        "part": "Part 2",
        "korean": (
            "바이러스는 다양한 방법으로 전파된다. 한 가지 전염 경로는 질병을"
            " 가진 유기체 - 매개체로 알려진 - 를 통해서인데, 예를 들어,"
            " 바이러스는 진딧물과 같은 식물 수액을 먹고 사는 곤충에 의해 종종"
            " 식물에서 식물로 전염되고 동물의 바이러스는 피를 빨아먹는 곤충에"
            " 의해 옮겨질 수 있다. 또한 기침이나 재채기와 같은 호흡기 활동으로"
            " 생성된 공기 중 입자를 통해 확산되는 바이러스도 많다. 이러한 공기"
            " 전염은 인플루엔자 바이러스, SARS-CoV-2, 수두, 천연두, 홍역과 같은"
            " 병원체에서 관찰된다. HIV는 성적 접촉, 그리고 감염된 혈액에 대한"
            " 노출을 통해 전염되는 몇몇 바이러스 중 하나이다."
        ),
        "english": (
            "Viruses spread in many ways. One transmission pathway is through"
            " disease-bearing organisms known as vectors: for example, viruses"
            " are often transmitted from plant to plant by insects that feed on"
            " plant sap, such as aphids; and viruses in animals can be carried"
            " by blood-sucking insects. Additionally, numerous viruses disperse"
            " through airborne particles generated by respiratory activities"
            " such as coughing and sneezing. This airborne transmission is"
            " observed in pathogens like influenza viruses, SARS-CoV-2,"
            " chickenpox, smallpox, and measles. HIV is one of several viruses"
            " transmitted through sexual contact and by exposure to infected"
            " blood."
        ),
    },
    {
        "part": "Part 3",
        "korean": (
            "면역 체계는 유기체를 질병으로부터 보호하는 생물학적 시스템의"
            " 네트워크이다. 암세포나 나무 파편 같은 물체를 포함하여 바이러스부터"
            " 기생충에 이르기까지 매우 다양한 병원체를 감지하고 이에 대응한다."
            " 면역 체계는 숙주를 감염으로부터 보호하기 위해, 특이성이 증가하는"
            " 계층적 방어 수단을 사용한다. 물리적 장벽은 세균 및 바이러스와 같은"
            " 병원체가 유기체에 침입하는 것을 방지한다. 만약 병원체가 이러한"
            " 장벽을 통과하면 선천적 면역 체계는 즉각적이지만 비특이적인 반응을"
            " 제공한다. 병원체가 선천적 면역 반응을 효과적으로 회피하는 경우,"
            " 척추동물은 적응 면역 체계라고 알려진 2차 방어선을 사용한다."
            " 여기에서 면역 체계는 병원체에 대한 인식을 개선하기 위해 감염 중"
            " 반응을 조정한다. 이렇게 개선된 반응은 병원체가 제거된 후에도"
            " 면역학적 기억의 형태로 유지되어, 이 병원체를 만날 때마다 적응"
            " 면역 체계가 더 빠르고 강력한 공격을 가할 수 있도록 한다."
        ),
        "english": (
            "The immune system is a network of biological systems that protects"
            " an organism from diseases. It detects and responds to a wide"
            " variety of pathogens, from viruses to parasitic worms, as well"
            " as cancer cells and objects such as wood splinters. The immune"
            " system employs layered defenses, increasing in specificity, to"
            " protect the host from infections. Physical barriers prevent"
            " pathogens such as bacteria and viruses from entering the"
            " organism. If a pathogen breaches these barriers, the innate"
            " immune system provides an immediate, but non-specific response."
            " In instances where pathogens effectively elude the innate immune"
            " response, vertebrates employ a secondary line of defense known"
            " as the adaptive immune system. Here, the immune system adapts"
            " its response during an infection to improve its recognition of"
            " the pathogen. This improved response is then retained after the"
            " pathogen has been eliminated, in the form of an immunological"
            " memory, and allows the adaptive immune system to mount faster"
            " and stronger attacks each time this pathogen is encountered."
        ),
    },
    {
        "part": "Part 4",
        "korean": (
            "백신은 질병에 대한 인체의 면역 반응을 촉진하기 위해 사용되는"
            " 제제이다. 백신의 안전성과 효능은 광범위한 정밀 조사와 검증을"
            " 거쳤다. 일반적으로 백신은 병원성 미생물과 유사하고 약화된 혹은"
            " 비활성화된 형태의 미생물, 독소, 혹은 표면 단백질 중 하나로부터"
            " 유래된 물질을 포함한다. 이 물질은 인체의 면역 체계로부터 반응을"
            " 이끌어내어 병원체를 인식하고 파괴하는 것을 용이하게 하며, 또한"
            " 면역학적 기억력 발달을 촉진하여 인지된 위협에 대비한다. 예방"
            " 접종은 전염병을 예방하는 가장 효과적인 수단으로 간주된다."
        ),
        "english": (
            "A vaccine is a preparation that is used to stimulate the body's"
            " immune response against diseases. The safety and efficacy of"
            " vaccines have undergone extensive scrutiny and validation."
            " Typically, a vaccine comprises an agent that resembles a"
            " pathogenic microorganism and is derived from attenuated or"
            " inactivated forms of the microbe, its toxins, or one of its"
            " surface proteins. This agent serves to elicit a response from"
            " the body's immune system, facilitating its recognition,"
            " destruction, and the development of immunological memory to"
            " guard against the perceived threat. Vaccination is considered as"
            " the most effective means of preventing infectious diseases."
        ),
    },
]

unit02_data = [
    {
        "part": "Part 1",
        "korean": (
            "고대 이집트는 기원전 3100년경에 일어난 인상적인 문명이었다. 기원전"
            " 332년에 마케도니아인들이 장악할 때까지 고대 이집트는 북아프리카와"
            " 인근 지역의 주요 강국으로 남아 있었다. 이 문명은 주로 나일강의"
            " 홍수 패턴을 농업에 최대한 활용했기 때문에 번성했다. 예측 가능한"
            " 홍수와 비옥한 계곡의 통제된 관개로 인해 잉여 농작물이 생산되었고,"
            " 이로 인해 인구가 증가하고 사회는 더욱 복잡해질 수 있었다."
            " 이집트인들은 환경과 자원을 성공적으로 관리함으로써 예술, 지식,"
            " 그리고 건축에서 풍성한 문화를 확립했으며 이는 이후 수 세기 동안"
            " 세계에 영향을 미치게 되었다."
        ),
        "english": (
            "Ancient Egypt was an impressive civilization that arose around"
            " 3100 B.C.E. It remained a major power in North Africa and nearby"
            " regions until the Macedonians took over in 332 B.C.E. This"
            " civilization flourished largely because it made the most of the"
            " Nile River's flooding patterns for agriculture. Controlled"
            " irrigation of the predictable floods and fertile valley produced"
            " surplus crops, which allowed the population to grow and society"
            " to become more complex. By successfully managing their"
            " environment and resources, Egyptians established a rich culture"
            " in art, knowledge, and architecture that would influence the"
            " world for centuries to come."
        ),
    },
    {
        "part": "Part 2",
        "korean": (
            "고대 이집트에서는 인구의 대부분이 농부로 구성되어 있었다. 그들의"
            " 집은 극심한 낮의 열기로부터 안식을 제공할 수 있도록 최적화된"
            " 디자인을 갖췄고, 진흙 벽돌로 지어졌다. 주식은 빵과 맥주로"
            " 이루어졌으며, 양파, 마늘과 같은 채소와 대추, 무화과와 같은"
            " 과일이 곁들여졌다. 위생과 개인적인 몸단장은 고대 이집트인들에게"
            " 매우 중요했다. 그들의 위생 시스템은 복잡했고 목욕, 면도, 치아"
            " 관리 등이 포함되었다. 많은 사람이 나일강에서 목욕했고, 동물성"
            " 지방과 백악질로 구성된 수제 반죽을 비누로 사용했다. 몸을 면도하는"
            " 것은 일반적인 관행이었고 향수와 향 오일은 불쾌한 냄새를 가리고"
            " 염증이 난 피부를 진정시키기 위해 사용되었다. 음악과 춤은"
            " 대중적인 오락이었다. 초기에는 플루트와 하프가 음악계를 지배했다."
            " 시간이 지남에 따라 트럼펫, 오보에 및 다양한 종류의 파이프를 닮은"
            " 다른 악기들이 소개되어 인기를 얻었다."
        ),
        "english": (
            "In ancient Egypt, the majority of the population was made up of"
            " farmers. Their houses were built from mudbrick with designs"
            " optimized to provide relief from the intense daytime heat. The"
            " staple diet consisted of bread and beer, supplemented with"
            " vegetables such as onions and garlic, and fruit such as dates and"
            " figs. Hygiene and personal grooming were of significant"
            " importance to the ancient Egyptians. Their hygiene system was"
            " complex, encompassing bathing, shaving, dental care, and more."
            " Many bathed in the Nile River, employing a homemade paste for"
            " soap composed of animal fat and chalk. Body shaving was a common"
            " practice and perfumes and scented oils were used to mask"
            " unpleasant smells and to calm irritated skin.\nMusic and dance"
            " were popular entertainments. Early on, the musical scene was"
            " dominated by flutes and harps. As time went on, other instruments"
            " resembling trumpets, oboes, and various types of pipes were"
            " introduced and gained popularity."
        ),
    },
    {
        "part": "Part 3",
        "korean": (
            "고대 이집트의 건축물에는 기자의 피라미드와 테베에 있는 사원들 등"
            " 세계에서 가장 유명한 건축물들이 포함되어 있다. 국가는 종교적이고"
            " 기념적인 목적을 위해서뿐만 아니라 파라오의 광범위한 권력을"
            " 강화하기 위해 건축 프로젝트를 조직하고 자금을 지원했다. 이 거대한"
            " 석조 건축물들은 파라오의 육체적, 정신적 본질을 수호하는 것으로"
            " 여겨졌다. 파라오의 영혼에서 매우 중요한 요소인 카는, 미래의"
            " 형태를 띤 파라오와 함께 거하고 있는 것으로 여겨졌다. 파라오의"
            " 시신을 세심하게 보존하는 것은 죽은 통치자가 사후 세계에서 죽은"
            " 자들의 군주로 책임을 다할 수 있도록 하는 데 중요했다. 고대"
            " 이집트의 기풍에서 이승에서의 죽음은 다음 세계로 향하는 여행의"
            " 시작이었다."
        ),
        "english": (
            "The architecture of ancient Egypt includes some of the most famous"
            " structures in the world: the Great Pyramids of Giza and the"
            " temples at Thebes. Building projects were organized and funded by"
            " the state not only for religious and commemorative purposes, but"
            " also to reinforce the wide-ranging power of the pharaoh. These"
            " massive stone structures were believed to safeguard the physical"
            " and spiritual essence of the pharaohs. The ka, which is a vital"
            " aspect of the pharaoh’s soul, was thought to dwell alongside"
            " their mummified forms. The meticulous preservation of the"
            " pharaoh’s body was crucial for enabling the departed ruler to"
            " adhere to his responsibilities in the afterlife as the monarch"
            " of the deceased."
        ),
    },
]


# 4. 공통 렌더링 함수
def render_unit(unit_title, unit_prefix, data_list):
    st.title(f"📖 {unit_title}")

    st.markdown(
        """
    본문 전체를 파트별로 나누었습니다. 각 파트의 한국어 해석을 보고 전체 영어 문단을 완성해 보세요.  
    * 💡 **채점 규칙**: 제출 후 단어 단위로 비교하여, **잘못 쓰거나 스펠링이 틀린 단어는 <span style='color:red; text-decoration:line-through;'>빨간색 취소선</span>**으로, **빼먹은 단어는 <span style='color:blue; text-decoration:underline;'>파란색 밑줄</span>**로 표시됩니다.
    """,
        unsafe_allow_html=True,
    )

    st.divider()

    for i, item in enumerate(data_list):
        st.subheader(f"📝 {item['part']}")
        st.info(item["korean"])

        user_input = st.text_area(
            f"{item['part']} 영어로 작성:",
            key=f"{unit_prefix}_input_{i}",
            height=150,
            placeholder="여기에 전체 영어 문단을 입력하세요...",
        )

        if st.button(
            f"{item['part']} 채점하기", key=f"{unit_prefix}_btn_{i}"
        ):
            if not user_input.strip():
                st.warning("영작 내용을 먼저 입력해 주세요!")
            else:
                st.markdown("### 🔍 채점 결과")
                diff_html = get_diff_html(item["english"], user_input)
                st.markdown(diff_html, unsafe_allow_html=True)

                st.markdown("### ✅ 완벽한 정답")
                st.success(item["english"])

        st.divider()


# 5. 페이지 변경 처리
if "selected_page" not in st.session_state:
    st.session_state.selected_page = "UNIT 01 Virus"


def change_page(page_name):
    st.session_state.selected_page = page_name


page = st.sidebar.radio(
    "원하는 단원을 선택하세요",
    ["UNIT 01 Virus", "UNIT 02 Ancient Egypt"],
    key="selected_page",
)

# 페이지 출력 및 이동 버튼 매핑
if page == "UNIT 01 Virus":
    render_unit("UNIT 01 Virus", "u1", unit01_data)
    st.button(
        "➡️ 다음 단원으로 이동 (UNIT 02)",
        on_click=change_page,
        args=("UNIT 02 Ancient Egypt",),
    )

elif page == "UNIT 02 Ancient Egypt":
    render_unit("UNIT 02 Ancient Egypt", "u2", unit02_data)
    st.button(
        "⬅️ 이전 단원으로 이동 (UNIT 01)",
        on_click=change_page,
        args=("UNIT 01 Virus",),
    )
