import streamlit as st
import difflib
import re

st.set_page_config(page_title="대학영어 워크북 영작하기", layout="wide")
st.title("📖 대학영어 워크북: 해석 보고 영작하기 (UNIT 01 Virus)")

# 데이터 정의 (Part 1 ~ Part 4 전체 본문)
data = [
    {
        "part": "Part 1",
        "korean": "바이러스는 유기체의 살아 있는 세포 내에서만 복제되는 초미세한 전염성 물질이다. 바이러스는 동물과 식물에서부터 미생물까지 모든 생명체를 감염시킨다. 바이러스 연구는 바이러스학이라고 하며, 이는 미생물학의 일부이다. 바이러스는 단백질 보호막으로 둘러싸인 유전 물질로 구성되어 있어 세균보다 죽이기가 더 어렵다. 바이러스 감염으로 인한 가벼운 질병의 경우, 질병이 자연스럽게 진행되도록 하는 것이 최선의 전략이다. 세균 감염과 싸우도록 고안된 항생제가 바이러스에 대해서는 효능이 부족하다는 것을 인식하는 것이 중요하다. 항생제는 바이러스를 죽이지 않으며 항생제를 사용하는 것은 항생제 내성으로 이어질 뿐이다.",
        "english": "A virus is a submicroscopic infectious agent that replicates only inside the living cells of an organism. Viruses infect all life forms, from animals and plants to microorganisms. The study of viruses is called virology, which is a part of microbiology. Viruses consist of genetic materials surrounded by a protective coat of protein, so they are more difficult to kill than bacteria. In the case of a minor ailment induced by a viral infection, the optimal strategy is to allow the malady to progress naturally. It is crucial to recognize that antibiotics, designed to combat bacterial infections, lack efficacy against viral entities. Antibiotics do not kill viruses and the use of them just leads to antibiotic resistance."
    },
    {
        "part": "Part 2",
        "korean": "바이러스는 다양한 방법으로 전파된다. 한 가지 전염 경로는 질병을 가진 유기체 - 매개체로 알려진 - 를 통해서인데, 예를 들어, 바이러스는 진딧물과 같은 식물 수액을 먹고 사는 곤충에 의해 종종 식물에서 식물로 전염되고 동물의 바이러스는 피를 빨아먹는 곤충에 의해 옮겨질 수 있다. 또한 기침이나 재채기와 같은 호흡기 활동으로 생성된 공기 중 입자를 통해 확산되는 바이러스도 많다. 이러한 공기 전염은 인플루엔자 바이러스, SARS-CoV-2, 수두, 천연두, 홍역과 같은 병원체에서 관찰된다. HIV는 성적 접촉, 그리고 감염된 혈액에 대한 노출을 통해 전염되는 몇몇 바이러스 중 하나이다.",
        "english": "Viruses spread in many ways. One transmission pathway is through disease-bearing organisms known as vectors: for example, viruses are often transmitted from plant to plant by insects that feed on plant sap, such as aphids; and viruses in animals can be carried by blood-sucking insects. Additionally, numerous viruses disperse through airborne particles generated by respiratory activities such as coughing and sneezing. This airborne transmission is observed in pathogens like influenza viruses, SARS-CoV-2, chickenpox, smallpox, and measles. HIV is one of several viruses transmitted through sexual contact and by exposure to infected blood."
    },
    {
        "part": "Part 3",
        "korean": "면역 체계는 유기체를 질병으로부터 보호하는 생물학적 시스템의 네트워크이다. 암세포나 나무 파편 같은 물체를 포함하여 바이러스부터 기생충에 이르기까지 매우 다양한 병원체를 감지하고 이에 대응한다. 면역 체계는 숙주를 감염으로부터 보호하기 위해, 특이성이 증가하는 계층적 방어 수단을 사용한다. 물리적 장벽은 세균 및 바이러스와 같은 병원체가 유기체에 침입하는 것을 방지한다. 만약 병원체가 이러한 장벽을 통과하면 선천적 면역 체계는 즉각적이지만 비특이적인 반응을 제공한다. 병원체가 선천적 면역 반응을 효과적으로 회피하는 경우, 척추동물은 적응 면역 체계라고 알려진 2차 방어선을 사용한다. 여기에서 면역 체계는 병원체에 대한 인식을 개선하기 위해 감염 중 반응을 조정한다. 이렇게 개선된 반응은 병원체가 제거된 후에도 면역학적 기억의 형태로 유지되어, 이 병원체를 만날 때마다 적응 면역 체계가 더 빠르고 강력한 공격을 가할 수 있도록 한다.",
        "english": "The immune system is a network of biological systems that protects an organism from diseases. It detects and responds to a wide variety of pathogens, from viruses to parasitic worms, as well as cancer cells and objects such as wood splinters. The immune system employs layered defenses, increasing in specificity, to protect the host from infections. Physical barriers prevent pathogens such as bacteria and viruses from entering the organism. If a pathogen breaches these barriers, the innate immune system provides an immediate, but non-specific response. In instances where pathogens effectively elude the innate immune response, vertebrates employ a secondary line of defense known as the adaptive immune system. Here, the immune system adapts its response during an infection to improve its recognition of the pathogen. This improved response is then retained after the pathogen has been eliminated, in the form of an immunological memory, and allows the adaptive immune system to mount faster and stronger attacks each time this pathogen is encountered."
    },
    {
        "part": "Part 4",
        "korean": "백신은 질병에 대한 인체의 면역 반응을 촉진하기 위해 사용되는 제제이다. 백신의 안전성과 효능은 광범위한 정밀 조사와 검증을 거쳤다. 일반적으로 백신은 병원성 미생물과 유사하고 약화된 혹은 비활성화된 형태의 미생물, 독소, 혹은 표면 단백질 중 하나로부터 유래된 물질을 포함한다. 이 물질은 인체의 면역 체계로부터 반응을 이끌어내어 병원체를 인식하고 파괴하는 것을 용이하게 하며, 또한 면역학적 기억력 발달을 촉진하여 인지된 위협에 대비한다. 예방 접종은 전염병을 예방하는 가장 효과적인 수단으로 간주된다.",
        "english": "A vaccine is a preparation that is used to stimulate the body's immune response against diseases. The safety and efficacy of vaccines have undergone extensive scrutiny and validation. Typically, a vaccine comprises an agent that resembles a pathogenic microorganism and is derived from attenuated or inactivated forms of the microbe, its toxins, or one of its surface proteins. This agent serves to elicit a response from the body's immune system, facilitating its recognition, destruction, and the development of immunological memory to guard against the perceived threat. Vaccination is considered as the most effective means of preventing infectious diseases."
    }
]

def get_diff_html(correct, user):
    """정답과 사용자 입력을 비교하여 틀린 부분을 HTML로 반환"""
    # 공백 기준으로 단어 분리
    correct_words = re.findall(r"\S+", correct)
    user_words = re.findall(r"\S+", user)
    
    # 단어 단위 비교
    diff = list(difflib.ndiff(correct_words, user_words))
    
    res = []
    for token in diff:
        word = token[2:]
        if token.startswith('  '):
            # 일치하는 부분 (기본 검정색)
            res.append(f"<span style='color: black;'>{word}</span>")
        elif token.startswith('- '):
            # 빠뜨린 부분 (정답에는 있으나 입력에는 없음) -> 파란색 밑줄
            res.append(f"<span style='color: blue; text-decoration: underline;' title='빠뜨린 단어'>{word}</span>")
        elif token.startswith('+ '):
            # 잘못 추가/틀린 부분 (정답에는 없으나 입력에 있음) -> 빨간색 취소선
            res.append(f"<span style='color: red; text-decoration: line-through;' title='틀린 단어'>{word}</span>")
            
    # 결과를 띄어쓰기로 연결하여 반환
    html_str = " ".join(res)
    return f'<div style="background-color: #f9f9f9; padding: 15px; border-radius: 5px; line-height: 1.6; font-size: 16px;">{html_str}</div>'

st.markdown("""
본문 전체를 4개의 파트로 나누었습니다. 각 파트의 한국어 해석을 보고 전체 영어 문단을 완성해 보세요.  
* 💡 **채점 규칙**: 제출 후 단어 단위로 비교하여, **잘못 쓰거나 스펠링이 틀린 단어는 <span style='color:red; text-decoration:line-through;'>빨간색 취소선</span>**으로, **빼먹은 단어는 <span style='color:blue; text-decoration:underline;'>파란색 밑줄</span>**로 표시됩니다.
""", unsafe_allow_html=True)

st.divider()

for i, item in enumerate(data):
    st.subheader(f"📝 {item['part']}")
    
    # 한국어 해석 보여주기
    st.info(item['korean'])
    
    # 사용자 입력 칸 (여러 줄 입력)
    user_input = st.text_area(f"{item['part']} 영어로 작성:", key=f"input_{i}", height=150, placeholder="여기에 전체 영어 문단을 입력하세요...")
    
    if st.button(f"{item['part']} 채점하기", key=f"btn_{i}"):
        if not user_input.strip():
            st.warning("영작 내용을 먼저 입력해 주세요!")
        else:
            st.markdown("### 🔍 채점 결과")
            diff_html = get_diff_html(item['english'], user_input)
            st.markdown(diff_html, unsafe_allow_html=True)
            
            st.markdown("### ✅ 완벽한 정답")
            st.success(item['english'])
            
    st.divider()
